### PR TITLE
Add companions to lists

### PR DESCRIPTION
**Pull request by MoMitch**
Companions are here for LOOT, check us out on https://www.companionsproject.io/

### CODE REVIEW

**Comment by noodlebuilds** [comment]
This is a project that's heavily inspired by Loot, we loved the blockchain experimentation and wanted to be a part of lootverse!

**Comment by Anish-Agnihotri** [comment]
Hey folks, can you please [verify your contract](https://etherscan.io/token/0x2aa7d4e9c306f406a6343fb558132a3fce7413d4#readContract) and then update this thread?

Just want to make sure users can verify what they are interacting with before I merge this PR!

**Comment by MoMitch** [comment]
Hi @Anish-Agnihotri - we have updated our contract and rebased the PR.

You can see our contract code at https://etherscan.io/address/0x2AA7d4E9C306F406A6343fB558132a3fCE7413d4

**Comment by Anish-Agnihotri** [comment]
Perfect, thank you. Merged!

**Pull request merged**
