### PR TITLE
Update lists.ts

### PR DESCRIPTION
**Pull request by oceanicnick**
Added Loot Deck of Many Things

## Project Name

Etherscan link: https://etherscan.io/address/0xb515bE4b1A1EF51b26bf268E96DB8FfFcE6b0Ff4#readContract

### CODE REVIEW

**Comment by domhofmann** [comment]
Please fix the conflict and add to bottom of list

**Comment by oceanicnick** [comment]
hi, I think thats it.

**Comment by ravindranrahul** [comment]
hey @oceanicnick , I think the conflicts were not resolved correctly. The build is breaking, Can you test it locally ? If its too confusing then pull in latest main branch and submit a new PR.

**Comment by oceanicnick** [comment]
Yeah I'll close this and do another request

**Pull request closed without merging**
