### PR TITLE
add Super Loot

### PR DESCRIPTION
**Pull request by zhulin0001**

### CODE REVIEW

**Comment by domhofmann** [comment]
Please rename "LOOT" to "Loot" and remove emojis

**Comment by zhulin0001** [comment]
> Please rename "LOOT" to "Loot" and remove emojis

Would you please recheck it? Thanks.

**Comment by zhulin0001** [comment]
We believe in all hero’s should have their cloaks like the Superman, so we add “back armor” and add more interesting gears inspired by Diablo and Wow.

**Comment by Anish-Agnihotri** [comment]
Requested changes confirmed, thank you!

**Pull request merged**
