### PR TITLE
Adding Cryptoodle project info for loot website

### PR DESCRIPTION
**Pull request by cryptoodles**
Cryptoodles Loot Bag

Etherscan link: https://etherscan.io/address/0x2a16107ea0d28ae822168c8bb3ef5460b1924a78#code

Website: https://cryptoodles.com

Twitter: https://twitter.com/cryptoodles

Discord: https://discord.com/invite/g9SnvzdFs2

OpenSea: https://opensea.io/collection/toodle-loot-bag

### CODE REVIEW

**Comment by ponderingdemocritus** [comment]
Thanks for the PR @cryptoodles

Could you please include your project on the resources page and remove it from the home page.

Please read here about homepage design principles - https://genesisproject.notion.site/Homepage-Design-Principles-245d17484a5b410692a117b31b4b38c6

**Comment by cryptoodles** [comment]
@ponderingdemocritus please check the above PR, fixed per your request

**Comment by cryptoodles** [comment]
@ponderingdemocritus please check the above PR, made changes per your request

**Comment by ponderingdemocritus** [comment]
Thank you!

**Pull request merged**
