### PR TITLE
Add color loot to developer tooling

### PR DESCRIPTION
**Pull request by lootavatars**
## Color Loot

Etherscan link: https://etherscan.io/address/0xab7f42a1a64f0f54d5428ab5e1243785bce3fcb3

Website: https://github.com/colorloot/colorloot

Twitter: https://twitter.com/lootavatars

### CODE REVIEW

**Comment by lootavatars** [comment]
We add color loot to developer tooling because color loot provides loot rarity data on chain, contract developers can call methods from Color Loot contract to get the item rarity. It's really helpful for developers building apps on Loot.

**Comment by domhofmann** [comment]
Hey there, I think this is still technically a derivative even though it san provide utility if it were fully minted

**Comment by ravindranrahul** [comment]
Hi @lootavatars are you still working on this?

**Comment by ravindranrahul** [comment]
@lootavatars closing the PR. Feel free to re open this.

**Pull request closed without merging**
