### PR TITLE
add Planets

### PR DESCRIPTION
**Pull request by sneg55**
Announcement https://twitter.com/LootPlanets/status/1433833720398553091

### CODE REVIEW

**Comment by sneg55** [comment]
@domhofmann can you please review and merge this PR? 

Thanks in advance!

**Comment by Anish-Agnihotri** [comment]
Hey, thanks for the PR! Could you please shorten the project description so it fits one line.

**Comment by sneg55** [comment]
@Anish-Agnihotri  done!

**Comment by Anish-Agnihotri** [comment]
Perfect, thanks for the prompt update. Merged!

**Pull request merged**
