### PR TITLE
Add Wizard Spells to list

### PR DESCRIPTION
**Pull request by aranair**
Add Wizard Spells to list

### CODE REVIEW

**Comment by domhofmann** [comment]
Please verify the contract so people can research.

**Comment by aranair** [comment]
> Please verify the contract so people can research.

@domhofmann - did you mean on etherscan? It should already be (https://etherscan.io/address/0x38e942948cea825992f105e0ec4a2ee9138afae4#code)

**Comment by aranair** [comment]
🤔 hmm, I guess let me resolve conflicts, and maybe I'll swap to the contract address instead of the token on etherscan

**Comment by Anish-Agnihotri** [comment]
Thanks for updating with verified contract. LGTM.

**Pull request merged**
