### PR TITLE
Add sexyLoot

### PR DESCRIPTION
**Pull request by sexyLoot**
sexyLoot (For Pleasure)

Etherscan link: https://etherscan.io/address/0xb13efab167751a95ec6f9844944c74aa668dded6

Website: https://opensea.io/collection/sexyloot

Twitter: https://twitter.com/LootSexy

### CODE REVIEW

**Comment by zhew2013** [comment]
Could you please resolve the conflict?

**Comment by sexyLoot** [comment]
What is the conflict? Sorry I don't understand. I'm not a dev. I followed instructions of forking the list of projects, adding mine, and submitting a pull. It's all a very complicated way to just supply the name/link/etherscan.
I can't see any button or label or indication of a conflict, or what to click, etc.

**Comment by zhew2013** [comment]
It means people have push to the main branch of code after you submit this PR, and your code branch is outdated and have difference with the main branch.

If you don't know how Git works, maybe the simplest way to do it is to:
1) go to your fork https://github.com/sexyLoot/website 
2) make sure you are on main branch (it should be)
3) You will see "This branch is 10 commits behind lootproject:main.", click "fetch upstream" and then "fetch and merge"
4) close this pull request, and open a new one like what you did before. (don't open with patch-1 branch, open with your new branch).

Another way to do it is to delete your fork, and then refork this project, and make your changes then submit a pull request.

It is way easier to do if you know how Git works, but otherwise, just follow my steps above and it should work. Just make sure you copy your few lines of changes before you delete your branch, in case you need your change.

**Comment by sexyLoot** [comment]
Thanks kindly, will do! Appreciate the tips, extremely good of you to help.

**Pull request closed without merging**
