### PR TITLE
add Loot Bibliotheca

### PR DESCRIPTION
**Pull request by magnetism2000**
**Added Loot Bibliotheca (for Adventurers) into the resource list.**

Loot Bibliotheca graphs approved community projects together so adventurers can see their progress in the Loot verse.

https://loot-bibliotheca-client.vercel.app/

### CODE REVIEW

**Comment by Anish-Agnihotri** [comment]
Thank for the PR! Could you please update the description so that it fits on one line like the others?

**Comment by oscarmanderj** [comment]
All fixed now!

**Comment by domhofmann** [comment]
Can you also drop the trailing period? Sorry, just going for consistency. :)

**Comment by oscarmanderj** [comment]
fixed now!

**Comment by Anish-Agnihotri** [comment]
Appreciate the changes :)! Merged.

**Comment by oscarmanderj** [comment]
Thank you!

**Pull request merged**
