### PR TITLE
Add Rings (for Loot) to the main page

### PR DESCRIPTION
**Pull request by w1nt3r-eth**
## Rings (for Loot)

Etherscan link: https://etherscan.io/address/0x73c5013Fa9701425be4a436cA0CeC1C0898e6F14

Website: https://rings.market/

Twitter: https://twitter.com/RingsforLoot

### CODE REVIEW

**Comment by w1nt3r-eth** [comment]
Hey folks, is there anything lacking here that would prevent the PR from being merged? Rings (for Loot) has launched yesterday and we would love to share it with the community.

**Comment by w1nt3r-eth** [comment]
@ponderingdemocritus any feedback on this PR? I know that readme instructions say to add the project to resource page first, but based on the listed criteria and the [Website Next Steps & Roadmap](https://genesisproject.notion.site/Website-Next-Steps-Roadmap-6eabdc58e63345699f4d4199cc1a250a) it would be great to have it in the "Gear Up" section.

**Comment by ponderingdemocritus** [comment]
have merged for now - will change the format of index page in a few days!

**Comment by w1nt3r-eth** [comment]
Thank you 🙏

**Pull request merged**
