### PR TITLE
Add Derivative: Dice (for Loot)

### PR DESCRIPTION
**Pull request by troq**
## Dice (for Loot)
Dice is randomized weighted dice generated and stored on chain. Some dice are more fair, others are luckier.

Etherscan link: https://etherscan.io/address/0x4Cec6Dca972BB810A1af1Ef3C8366B22b390c5Bc

Website: https://diceforloot.com

Twitter: https://twitter.com/DiceForLoot

Discord: https://discord.gg/z6fbJcAADj

### CODE REVIEW

**Comment by ravindranrahul** [comment]
Thanks for the PR! Small nit: could you shorten the description to make it fit on one like the others?

**Comment by troq** [comment]
> Thanks for the PR! Small nit: could you shorten the description to make it fit on one like the others?

@ravindranrahul just updated. Is that good?

**Comment by ravindranrahul** [comment]
Awesome! Description looks good. Few more things:

- Please remove the trailing period from the description.

- Can you please resolve the conflicts? While you work on the conflict, please ensure list items are ordered alphabetically.

**Comment by troq** [comment]
@ravindranrahul done!

**Comment by ravindranrahul** [comment]
Hey Please resolve the conflicts so we can merge this.

**Comment by troq** [comment]
@ravindranrahul done. Can you merge now?

**Comment by ravindranrahul** [comment]
Yep looks good! Thanks for your contribution

**Pull request merged**
